name: Test and build

on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Check types
        run: npm run typecheck
        env:
          CI: true

      - name: Check formatting
        run: npm run prettier
        env:
          CI: true

      - name: Lint
        run: npm run lint
        env:
          CI: true

  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Build
        run: npm run build
        env:
          CI: true
